export const GET_MOVIES_LOADING = "GET_MOVIES_LOADING"
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS"
export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR"
export const GET_MOVIES_UPDATE = "GET_MOVIES_UPDATE"
export const RATING_UPDATE="RATING_UPDATE"
export const WATCH_STATUS_UPDATE="WATCH_STATUS_UPDATE"

